## [Numpy](https://numpy.org/)
NumPy es el paquete fundamental para la computación científica en Python. Es una biblioteca de Python que proporciona un objeto de matriz multidimensional, varios objetos derivados y una variedad de rutinas para operaciones rápidas en matrices, que incluyen manipulación matemática, lógica, clasificación, selección, E/S, transformadas discretas de Fourier, álgebra lineal, operaciones estadísticas, simulación aleatoria y mucho más.


In [1]:
import numpy as np

In [3]:
array = np.array([1,2,3,4,5])

In [6]:
type(array)

numpy.ndarray

In [11]:
# Tamaño de una matriz
array.shape

(5,)

In [14]:
array2 = np.array([1,2,3,4,5,6,7,8,9])
array2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
array2.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
array2.ndim

1

In [24]:
array3 = array2.reshape(3,3)

In [26]:
array3.ndim

2

In [28]:
array3.dtype.name

'int64'

In [31]:
array3.size

9

In [37]:
array4 = np.zeros((3,4))
array4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [40]:
array5 = np.ones((4,4))
array5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [81]:
array6 = np.linspace(0,10,20)
array6

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [83]:
array7 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
array7

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [85]:
array8 = np.array([[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
array8

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [86]:
array7 + array8

array([[17, 19, 21, 23, 25],
       [27, 29, 31, 33, 35],
       [37, 39, 41, 43, 45]])

In [88]:
array7 - array8

array([[-15, -15, -15, -15, -15],
       [-15, -15, -15, -15, -15],
       [-15, -15, -15, -15, -15]])

In [91]:
array7/array8

array([[0.0625    , 0.11764706, 0.16666667, 0.21052632, 0.25      ],
       [0.28571429, 0.31818182, 0.34782609, 0.375     , 0.4       ],
       [0.42307692, 0.44444444, 0.46428571, 0.48275862, 0.5       ]])

In [93]:
np.sin(array7)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [95]:
np.exp(array8)

array([[8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
        4.85165195e+08],
       [1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
        7.20048993e+10],
       [1.95729609e+11, 5.32048241e+11, 1.44625706e+12, 3.93133430e+12,
        1.06864746e+13]])

In [97]:
array8

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [99]:
array8.T

array([[16, 21, 26],
       [17, 22, 27],
       [18, 23, 28],
       [19, 24, 29],
       [20, 25, 30]])

In [101]:
array8.max()

30

In [105]:
array8.min()

16